# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/web-p1/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
